export type SurahIndexItem = {
  nomor: number
  id: string
  namaLatin: string
  arti: string
  jumlahAyat: number
}

export const surahIndex: SurahIndexItem[] = [
  { nomor: 1, id: "al-fatihah", namaLatin: "Al-Fatihah", arti: "Pembukaan", jumlahAyat: 7 },
  { nomor: 2, id: "al-baqarah", namaLatin: "Al-Baqarah", arti: "Sapi", jumlahAyat: 286 },
  { nomor: 3, id: "ali-imran", namaLatin: "Ali 'Imran", arti: "Keluarga Imran", jumlahAyat: 200 },
  { nomor: 4, id: "an-nisa", namaLatin: "An-Nisa", arti: "Wanita", jumlahAyat: 176 },
  { nomor: 5, id: "al-maidah", namaLatin: "Al-Ma'idah", arti: "Hidangan", jumlahAyat: 120 },
  { nomor: 6, id: "al-anam", namaLatin: "Al-An'am", arti: "Binatang Ternak", jumlahAyat: 165 },
  { nomor: 7, id: "al-araaf", namaLatin: "Al-A'raf", arti: "Tempat Tertinggi", jumlahAyat: 206 },
  { nomor: 8, id: "al-anfal", namaLatin: "Al-Anfal", arti: "Rampasan", jumlahAyat: 75 },
  { nomor: 9, id: "at-taubah", namaLatin: "At-Taubah", arti: "Pertobatan", jumlahAyat: 129 },
  { nomor: 10, id: "yunus", namaLatin: "Yunus", arti: "Yunus", jumlahAyat: 109 },
  { nomor: 11, id: "hud", namaLatin: "Hud", arti: "Hud", jumlahAyat: 123 },
  { nomor: 12, id: "yusuf", namaLatin: "Yusuf", arti: "Yusuf", jumlahAyat: 111 },
  { nomor: 13, id: "ar-ra'd", namaLatin: "Ar-Ra'd", arti: "Guruh", jumlahAyat: 43 },
  { nomor: 14, id: "ibrahim", namaLatin: "Ibrahim", arti: "Ibrahim", jumlahAyat: 52 },
  { nomor: 15, id: "al-hijr", namaLatin: "Al-Hijr", arti: "Hijr", jumlahAyat: 99 },
  { nomor: 16, id: "an-nahl", namaLatin: "An-Nahl", arti: "Lebah", jumlahAyat: 128 },
  { nomor: 17, id: "al-isra", namaLatin: "Al-Isra", arti: "Perjalanan Malam", jumlahAyat: 111 },
  { nomor: 18, id: "al-kahf", namaLatin: "Al-Kahf", arti: "Gua", jumlahAyat: 110 },
  { nomor: 19, id: "maryam", namaLatin: "Maryam", arti: "Maryam", jumlahAyat: 98 },
  { nomor: 20, id: "ta-ha", namaLatin: "Ta-Ha", arti: "Ta Ha", jumlahAyat: 135 },
  { nomor: 21, id: "al-anbiya", namaLatin: "Al-Anbiya", arti: "Para Nabi", jumlahAyat: 112 },
  { nomor: 22, id: "al-hajj", namaLatin: "Al-Hajj", arti: "Haji", jumlahAyat: 78 },
  { nomor: 23, id: "al-muminun", namaLatin: "Al-Mu'minun", arti: "Orang Beriman", jumlahAyat: 118 },
  { nomor: 24, id: "an-nur", namaLatin: "An-Nur", arti: "Cahaya", jumlahAyat: 64 },
  { nomor: 25, id: "al-furqan", namaLatin: "Al-Furqan", arti: "Pembeda", jumlahAyat: 77 },
  { nomor: 26, id: "asy-syuara", namaLatin: "Asy-Syu'ara", arti: "Para Penyair", jumlahAyat: 227 },
  { nomor: 27, id: "an-naml", namaLatin: "An-Naml", arti: "Semut", jumlahAyat: 93 },
  { nomor: 28, id: "al-qasas", namaLatin: "Al-Qasas", arti: "Kisah", jumlahAyat: 88 },
  { nomor: 29, id: "al-ankabut", namaLatin: "Al-'Ankabut", arti: "Laba-laba", jumlahAyat: 69 },
  { nomor: 30, id: "ar-rum", namaLatin: "Ar-Rum", arti: "Romawi", jumlahAyat: 60 },
  { nomor: 31, id: "luqman", namaLatin: "Luqman", arti: "Luqman", jumlahAyat: 34 },
  { nomor: 32, id: "as-sajdah", namaLatin: "As-Sajdah", arti: "Sujud", jumlahAyat: 30 },
  { nomor: 33, id: "al-ahzab", namaLatin: "Al-Ahzab", arti: "Golongan yang Bersekutu", jumlahAyat: 73 },
  { nomor: 34, id: "saba", namaLatin: "Saba", arti: "Saba", jumlahAyat: 54 },
  { nomor: 35, id: "fatir", namaLatin: "Fatir", arti: "Pencipta", jumlahAyat: 45 },
  { nomor: 36, id: "ya-sin", namaLatin: "Ya-Sin", arti: "Ya Sin", jumlahAyat: 83 },
  { nomor: 37, id: "as-saffat", namaLatin: "As-Saffat", arti: "Barisan", jumlahAyat: 182 },
  { nomor: 38, id: "sad", namaLatin: "Sad", arti: "Sad", jumlahAyat: 88 },
  { nomor: 39, id: "az-zumar", namaLatin: "Az-Zumar", arti: "Rombongan", jumlahAyat: 75 },
  { nomor: 40, id: "ghafir", namaLatin: "Ghafir", arti: "Pengampun", jumlahAyat: 85 },
  { nomor: 41, id: "fussilat", namaLatin: "Fussilat", arti: "Yang Dijelaskan", jumlahAyat: 54 },
  { nomor: 42, id: "asy-syura", namaLatin: "Asy-Syura", arti: "Musyawarah", jumlahAyat: 53 },
  { nomor: 43, id: "az-zukhruf", namaLatin: "Az-Zukhruf", arti: "Perhiasan", jumlahAyat: 89 },
  { nomor: 44, id: "ad-dukhan", namaLatin: "Ad-Dukhan", arti: "Asap", jumlahAyat: 59 },
  { nomor: 45, id: "al-jathiyah", namaLatin: "Al-Jathiyah", arti: "Yang Berlutut", jumlahAyat: 37 },
  { nomor: 46, id: "al-ahqaf", namaLatin: "Al-Ahqaf", arti: "Bukit Pasir", jumlahAyat: 35 },
  { nomor: 47, id: "muhammad", namaLatin: "Muhammad", arti: "Muhammad", jumlahAyat: 38 },
  { nomor: 48, id: "al-fath", namaLatin: "Al-Fath", arti: "Kemenangan", jumlahAyat: 29 },
  { nomor: 49, id: "al-hujurat", namaLatin: "Al-Hujurat", arti: "Kamar-Kamar", jumlahAyat: 18 },
  { nomor: 50, id: "qaf", namaLatin: "Qaf", arti: "Qaf", jumlahAyat: 45 },
  { nomor: 51, id: "adz-dzariyat", namaLatin: "Adz-Dzariyat", arti: "Angin yang Menerbangkan", jumlahAyat: 60 },
  { nomor: 52, id: "at-tur", namaLatin: "At-Tur", arti: "Bukit", jumlahAyat: 49 },
  { nomor: 53, id: "an-najm", namaLatin: "An-Najm", arti: "Bintang", jumlahAyat: 62 },
  { nomor: 54, id: "al-qamar", namaLatin: "Al-Qamar", arti: "Bulan", jumlahAyat: 55 },
  { nomor: 55, id: "ar-rahman", namaLatin: "Ar-Rahman", arti: "Yang Maha Pemurah", jumlahAyat: 78 },
  { nomor: 56, id: "al-waqiah", namaLatin: "Al-Waqi'ah", arti: "Hari Kiamat", jumlahAyat: 96 },
  { nomor: 57, id: "al-hadid", namaLatin: "Al-Hadid", arti: "Besi", jumlahAyat: 29 },
  { nomor: 58, id: "al-mujadila", namaLatin: "Al-Mujadila", arti: "Gugatan", jumlahAyat: 22 },
  { nomor: 59, id: "al-hasyr", namaLatin: "Al-Hasyr", arti: "Pengusiran", jumlahAyat: 24 },
  { nomor: 60, id: "al-mumtahanah", namaLatin: "Al-Mumtahanah", arti: "Wanita yang Diuji", jumlahAyat: 13 },
  { nomor: 61, id: "as-saff", namaLatin: "As-Saff", arti: "Barisan", jumlahAyat: 14 },
  { nomor: 62, id: "al-jumuah", namaLatin: "Al-Jumu'ah", arti: "Hari Jumat", jumlahAyat: 11 },
  { nomor: 63, id: "al-munafiqun", namaLatin: "Al-Munafiqun", arti: "Orang Munafik", jumlahAyat: 11 },
  { nomor: 64, id: "at-taghabun", namaLatin: "At-Taghabun", arti: "Hari Ditampakkan Kesalahan", jumlahAyat: 18 },
  { nomor: 65, id: "at-talaq", namaLatin: "At-Talaq", arti: "Talak", jumlahAyat: 12 },
  { nomor: 66, id: "at-tahrim", namaLatin: "At-Tahrim", arti: "Pengharaman", jumlahAyat: 12 },
  { nomor: 67, id: "al-mulk", namaLatin: "Al-Mulk", arti: "Kerajaan", jumlahAyat: 30 },
  { nomor: 68, id: "al-qalam", namaLatin: "Al-Qalam", arti: "Pen", jumlahAyat: 68 },
  { nomor: 69, id: "al-haqqah", namaLatin: "Al-Haqqah", arti: "Yang Hakiki", jumlahAyat: 52 },
  { nomor: 70, id: "al-maarij", namaLatin: "Al-Ma'arij", arti: "Tempat Naik", jumlahAyat: 44 },
  { nomor: 71, id: "nuh", namaLatin: "Nuh", arti: "Nuh", jumlahAyat: 28 },
  { nomor: 72, id: "al-jinn", namaLatin: "Al-Jinn", arti: "Jin", jumlahAyat: 28 },
  { nomor: 73, id: "al-muzzammil", namaLatin: "Al-Muzzammil", arti: "Yang Berselimut", jumlahAyat: 20 },
  { nomor: 74, id: "al-muddaththir", namaLatin: "Al-Muddaththir", arti: "Yang Membungkus", jumlahAyat: 56 },
  { nomor: 75, id: "al-qiyamah", namaLatin: "Al-Qiyamah", arti: "Hari Kiamat", jumlahAyat: 40 },
  { nomor: 76, id: "al-insan", namaLatin: "Al-Insan", arti: "Manusia", jumlahAyat: 31 },
  { nomor: 77, id: "al-mursalat", namaLatin: "Al-Mursalat", arti: "Yang Dutus", jumlahAyat: 50 },
  { nomor: 78, id: "an-naba", namaLatin: "An-Naba", arti: "Berita Besar", jumlahAyat: 40 },
  { nomor: 79, id: "an-nazi'at", namaLatin: "An-Nazi'at", arti: "Malaikat Pencabut", jumlahAyat: 46 },
  { nomor: 80, id: "abasa", namaLatin: "Abasa", arti: "Ia Bermasam Muka", jumlahAyat: 42 },
  { nomor: 81, id: "at-takwir", namaLatin: "At-Takwir", arti: "Penggulungan", jumlahAyat: 29 },
  { nomor: 82, id: "al-infitar", namaLatin: "Al-Infitar", arti: "Terbelah", jumlahAyat: 19 },
  { nomor: 83, id: "al-mutaffifin", namaLatin: "Al-Mutaffifin", arti: "Orang yang Curang", jumlahAyat: 36 },
  { nomor: 84, id: "al-inshiqaq", namaLatin: "Al-Inshiqaq", arti: "Terbelah", jumlahAyat: 25 },
  { nomor: 85, id: "al-buruj", namaLatin: "Al-Buruj", arti: "Gugusan Bintang", jumlahAyat: 22 },
  { nomor: 86, id: "at-tariq", namaLatin: "At-Tariq", arti: "Yang Datang di Malam Hari", jumlahAyat: 17 },
  { nomor: 87, id: "al-ala", namaLatin: "Al-A'la", arti: "Yang Paling Tinggi", jumlahAyat: 19 },
  { nomor: 88, id: "al-ghashiyah", namaLatin: "Al-Ghashiyah", arti: "Hari Kiamat", jumlahAyat: 26 },
  { nomor: 89, id: "al-fajr", namaLatin: "Al-Fajr", arti: "Fajar", jumlahAyat: 30 },
  { nomor: 90, id: "al-balad", namaLatin: "Al-Balad", arti: "Negeri", jumlahAyat: 20 },
  { nomor: 91, id: "asy-syams", namaLatin: "Asy-Syams", arti: "Matahari", jumlahAyat: 15 },
  { nomor: 92, id: "al-lail", namaLatin: "Al-Lail", arti: "Malam", jumlahAyat: 21 },
  { nomor: 93, id: "ad-duha", namaLatin: "Ad-Duha", arti: "Waktu Dhuha", jumlahAyat: 11 },
  { nomor: 94, id: "asy-syarh", namaLatin: "Asy-Syarh", arti: "Kelapangan", jumlahAyat: 8 },
  { nomor: 95, id: "at-tin", namaLatin: "At-Tin", arti: "Buah Tin", jumlahAyat: 8 },
  { nomor: 96, id: "al-alaq", namaLatin: "Al-'Alaq", arti: "Segumpal Darah", jumlahAyat: 19 },
  { nomor: 97, id: "al-qadr", namaLatin: "Al-Qadr", arti: "Kemuliaan", jumlahAyat: 5 },
  { nomor: 98, id: "al-bayyinah", namaLatin: "Al-Bayyinah", arti: "Bukti Nyata", jumlahAyat: 8 },
  { nomor: 99, id: "az-zalzalah", namaLatin: "Az-Zalzalah", arti: "Kegoncangan", jumlahAyat: 8 },
  { nomor: 100, id: "al-adiyat", namaLatin: "Al-'Adiyat", arti: "Kuda yang Berlari Kencang", jumlahAyat: 11 },
  { nomor: 101, id: "al-qariah", namaLatin: "Al-Qari'ah", arti: "Hari Kiamat", jumlahAyat: 11 },
  { nomor: 102, id: "at-takathur", namaLatin: "At-Takathur", arti: "Bermegah-megahan", jumlahAyat: 8 },
  { nomor: 103, id: "al-asr", namaLatin: "Al-'Asr", arti: "Waktu", jumlahAyat: 3 },
  { nomor: 104, id: "al-humazah", namaLatin: "Al-Humazah", arti: "Pengumpat", jumlahAyat: 9 },
  { nomor: 105, id: "al-fil", namaLatin: "Al-Fil", arti: "Gajah", jumlahAyat: 5 },
  { nomor: 106, id: "quraisy", namaLatin: "Quraisy", arti: "Quraisy", jumlahAyat: 4 },
  { nomor: 107, id: "al-maun", namaLatin: "Al-Ma'un", arti: "Barang yang Berguna", jumlahAyat: 7 },
  { nomor: 108, id: "al-kauthar", namaLatin: "Al-Kauthar", arti: "Nikmat yang Banyak", jumlahAyat: 3 },
  { nomor: 109, id: "al-kafirun", namaLatin: "Al-Kafirun", arti: "Orang Kafir", jumlahAyat: 6 },
  { nomor: 110, id: "an-nasr", namaLatin: "An-Nasr", arti: "Pertolongan", jumlahAyat: 3 },
  { nomor: 111, id: "al-lahab", namaLatin: "Al-Lahab", arti: "Api", jumlahAyat: 5 },
  { nomor: 112, id: "al-ikhlas", namaLatin: "Al-Ikhlas", arti: "Ikhlas", jumlahAyat: 4 },
  { nomor: 113, id: "al-falaq", namaLatin: "Al-Falaq", arti: "Waktu Subuh", jumlahAyat: 5 },
  { nomor: 114, id: "an-nas", namaLatin: "An-Nas", arti: "Manusia", jumlahAyat: 6 },
]
