export type SurahDetailMeta = {
  nomor: number
  id: string
  namaLatin: string
  namaArab: string
  arti: string
  jumlahAyat: number
  tempatTurun: "Makkiyah" | "Madaniyah"
}

export const SURAH_DETAIL_LIST: SurahDetailMeta[] = [
  { nomor: 1, id: "al-fatihah", namaLatin: "Al-Fatihah", namaArab: "الفاتحة", arti: "Pembukaan", jumlahAyat: 7, tempatTurun: "Makkiyah" },
  { nomor: 2, id: "al-baqarah", namaLatin: "Al-Baqarah", namaArab: "البقرة", arti: "Sapi", jumlahAyat: 286, tempatTurun: "Madaniyah" },
  { nomor: 3, id: "ali-imran", namaLatin: "Ali 'Imran", namaArab: "آل عمران", arti: "Keluarga Imran", jumlahAyat: 200, tempatTurun: "Madaniyah" },
  { nomor: 4, id: "an-nisa", namaLatin: "An-Nisa", namaArab: "النساء", arti: "Wanita", jumlahAyat: 176, tempatTurun: "Madaniyah" },
  { nomor: 5, id: "al-maidah", namaLatin: "Al-Ma'idah", namaArab: "المائدة", arti: "Hidangan", jumlahAyat: 120, tempatTurun: "Madaniyah" },
  { nomor: 6, id: "al-anam", namaLatin: "Al-An'am", namaArab: "الأنعام", arti: "Binatang Ternak", jumlahAyat: 165, tempatTurun: "Makkiyah" },
  { nomor: 7, id: "al-araaf", namaLatin: "Al-A'raf", namaArab: "الأعراف", arti: "Tempat Tertinggi", jumlahAyat: 206, tempatTurun: "Makkiyah" },
  { nomor: 8, id: "al-anfal", namaLatin: "Al-Anfal", namaArab: "الأنفال", arti: "Rampasan Perang", jumlahAyat: 75, tempatTurun: "Madaniyah" },
  { nomor: 9, id: "at-taubah", namaLatin: "At-Taubah", namaArab: "التوبة", arti: "Pengampunan", jumlahAyat: 129, tempatTurun: "Madaniyah" },
  { nomor: 10, id: "yunus", namaLatin: "Yunus", namaArab: "يونس", arti: "Yunus", jumlahAyat: 109, tempatTurun: "Makkiyah" },
  { nomor: 11, id: "hud", namaLatin: "Hud", namaArab: "هود", arti: "Hud", jumlahAyat: 123, tempatTurun: "Makkiyah" },
  { nomor: 12, id: "yusuf", namaLatin: "Yusuf", namaArab: "يوسف", arti: "Yusuf", jumlahAyat: 111, tempatTurun: "Makkiyah" },
  { nomor: 13, id: "ar-ra'd", namaLatin: "Ar-Ra'd", namaArab: "الرعد", arti: "Guruh", jumlahAyat: 43, tempatTurun: "Madaniyah" },
  { nomor: 14, id: "ibrahim", namaLatin: "Ibrahim", namaArab: "إبراهيم", arti: "Ibrahim", jumlahAyat: 52, tempatTurun: "Makkiyah" },
  { nomor: 15, id: "al-hijr", namaLatin: "Al-Hijr", namaArab: "الحجر", arti: "Negeri Kaum Tsamud", jumlahAyat: 99, tempatTurun: "Makkiyah" },
  { nomor: 16, id: "an-nahl", namaLatin: "An-Nahl", namaArab: "النحل", arti: "Lebah", jumlahAyat: 128, tempatTurun: "Makkiyah" },
  { nomor: 17, id: "al-isra", namaLatin: "Al-Isra", namaArab: "الإسراء", arti: "Perjalanan Malam", jumlahAyat: 111, tempatTurun: "Makkiyah" },
  { nomor: 18, id: "al-kahf", namaLatin: "Al-Kahf", namaArab: "الكهف", arti: "Gua", jumlahAyat: 110, tempatTurun: "Makkiyah" },
  { nomor: 19, id: "maryam", namaLatin: "Maryam", namaArab: "مريم", arti: "Maryam", jumlahAyat: 98, tempatTurun: "Makkiyah" },
  { nomor: 20, id: "ta-ha", namaLatin: "Ta-Ha", namaArab: "طه", arti: "Ta Ha", jumlahAyat: 135, tempatTurun: "Makkiyah" },
  { nomor: 21, id: "al-anbiya", namaLatin: "Al-Anbiya", namaArab: "الأنبياء", arti: "Para Nabi", jumlahAyat: 112, tempatTurun: "Makkiyah" },
  { nomor: 22, id: "al-hajj", namaLatin: "Al-Hajj", namaArab: "الحج", arti: "Haji", jumlahAyat: 78, tempatTurun: "Madaniyah" },
  { nomor: 23, id: "al-muminun", namaLatin: "Al-Mu'minun", namaArab: "المؤمنون", arti: "Orang-Orang Mukmin", jumlahAyat: 118, tempatTurun: "Makkiyah" },
  { nomor: 24, id: "an-nur", namaLatin: "An-Nur", namaArab: "النور", arti: "Cahaya", jumlahAyat: 64, tempatTurun: "Madaniyah" },
  { nomor: 25, id: "al-furqan", namaLatin: "Al-Furqan", namaArab: "الفرقان", arti: "Pembeda", jumlahAyat: 77, tempatTurun: "Makkiyah" },
  { nomor: 26, id: "asy-syuara", namaLatin: "Asy-Syu'ara", namaArab: "الشعراء", arti: "Para Penyair", jumlahAyat: 227, tempatTurun: "Makkiyah" },
  { nomor: 27, id: "an-naml", namaLatin: "An-Naml", namaArab: "النمل", arti: "Semut", jumlahAyat: 93, tempatTurun: "Makkiyah" },
  { nomor: 28, id: "al-qasas", namaLatin: "Al-Qasas", namaArab: "القصص", arti: "Kisah-Kisah", jumlahAyat: 88, tempatTurun: "Makkiyah" },
  { nomor: 29, id: "al-ankabut", namaLatin: "Al-'Ankabut", namaArab: "العنكبوت", arti: "Laba-Laba", jumlahAyat: 69, tempatTurun: "Makkiyah" },
  { nomor: 30, id: "ar-rum", namaLatin: "Ar-Rum", namaArab: "الروم", arti: "Bangsa Romawi", jumlahAyat: 60, tempatTurun: "Makkiyah" },
  { nomor: 31, id: "luqman", namaLatin: "Luqman", namaArab: "لقمان", arti: "Keluarga Luqman", jumlahAyat: 34, tempatTurun: "Makkiyah" },
  { nomor: 32, id: "as-sajdah", namaLatin: "As-Sajdah", namaArab: "السجدة", arti: "Sujud", jumlahAyat: 30, tempatTurun: "Makkiyah" },
  { nomor: 33, id: "al-ahzab", namaLatin: "Al-Ahzab", namaArab: "الأحزاب", arti: "Golongan yang Bersekutu", jumlahAyat: 73, tempatTurun: "Madaniyah" },
  { nomor: 34, id: "saba", namaLatin: "Saba", namaArab: "سبإ", arti: "Kaum Saba'", jumlahAyat: 54, tempatTurun: "Makkiyah" },
  { nomor: 35, id: "fatir", namaLatin: "Fatir", namaArab: "فاطر", arti: "Pencipta", jumlahAyat: 45, tempatTurun: "Makkiyah" },
  { nomor: 36, id: "ya-sin", namaLatin: "Ya-Sin", namaArab: "يس", arti: "Ya Sin", jumlahAyat: 83, tempatTurun: "Makkiyah" },
  { nomor: 37, id: "as-saffat", namaLatin: "As-Saffat", namaArab: "الصافات", arti: "Barisan-Barisan", jumlahAyat: 182, tempatTurun: "Makkiyah" },
  { nomor: 38, id: "sad", namaLatin: "Sad", namaArab: "ص", arti: "Shad", jumlahAyat: 88, tempatTurun: "Makkiyah" },
  { nomor: 39, id: "az-zumar", namaLatin: "Az-Zumar", namaArab: "الزمر", arti: "Rombongan-Rombongan", jumlahAyat: 75, tempatTurun: "Makkiyah" },
  { nomor: 40, id: "ghafir", namaLatin: "Ghafir", namaArab: "غافر", arti: "Yang Mengampuni", jumlahAyat: 85, tempatTurun: "Makkiyah" },
  { nomor: 41, id: "fussilat", namaLatin: "Fussilat", namaArab: "فصلت", arti: "Yang Dijelaskan", jumlahAyat: 54, tempatTurun: "Makkiyah" },
  { nomor: 42, id: "asy-syura", namaLatin: "Asy-Syura", namaArab: "الشورى", arti: "Musyawarah", jumlahAyat: 53, tempatTurun: "Makkiyah" },
  { nomor: 43, id: "az-zukhruf", namaLatin: "Az-Zukhruf", namaArab: "الزخرف", arti: "Perhiasan", jumlahAyat: 89, tempatTurun: "Makkiyah" },
  { nomor: 44, id: "ad-dukhan", namaLatin: "Ad-Dukhan", namaArab: "الدخان", arti: "Kabut / Asap", jumlahAyat: 59, tempatTurun: "Makkiyah" },
  { nomor: 45, id: "al-jathiyah", namaLatin: "Al-Jathiyah", namaArab: "الجاثية", arti: "Yang Berlutut", jumlahAyat: 37, tempatTurun: "Makkiyah" },
  { nomor: 46, id: "al-ahqaf", namaLatin: "Al-Ahqaf", namaArab: "الأحقاف", arti: "Bukit-Bukit Pasir", jumlahAyat: 35, tempatTurun: "Makkiyah" },
  { nomor: 47, id: "muhammad", namaLatin: "Muhammad", namaArab: "محمد", arti: "Nabi Muhammad", jumlahAyat: 38, tempatTurun: "Madaniyah" },
  { nomor: 48, id: "al-fath", namaLatin: "Al-Fath", namaArab: "الفتح", arti: "Kemenangan", jumlahAyat: 29, tempatTurun: "Madaniyah" },
  { nomor: 49, id: "al-hujurat", namaLatin: "Al-Hujurat", namaArab: "الحجرات", arti: "Kamar-Kamar", jumlahAyat: 18, tempatTurun: "Madaniyah" },
  { nomor: 50, id: "qaf", namaLatin: "Qaf", namaArab: "ق", arti: "Qaf", jumlahAyat: 45, tempatTurun: "Makkiyah" },
  { nomor: 51, id: "adz-dzariyat", namaLatin: "Adz-Dzariyat", namaArab: "الذاريات", arti: "Angin yang Menerbangkan", jumlahAyat: 60, tempatTurun: "Makkiyah" },
  { nomor: 52, id: "at-tur", namaLatin: "At-Tur", namaArab: "الطور", arti: "Bukit Tursina", jumlahAyat: 49, tempatTurun: "Makkiyah" },
  { nomor: 53, id: "an-najm", namaLatin: "An-Najm", namaArab: "النجم", arti: "Bintang", jumlahAyat: 62, tempatTurun: "Makkiyah" },
  { nomor: 54, id: "al-qamar", namaLatin: "Al-Qamar", namaArab: "القمر", arti: "Bulan", jumlahAyat: 55, tempatTurun: "Makkiyah" },
  { nomor: 55, id: "ar-rahman", namaLatin: "Ar-Rahman", namaArab: "الرحمن", arti: "Yang Maha Pengasih", jumlahAyat: 78, tempatTurun: "Madaniyah" },
  { nomor: 56, id: "al-waqiah", namaLatin: "Al-Waqi'ah", namaArab: "الواقعة", arti: "Hari Kiamat", jumlahAyat: 96, tempatTurun: "Makkiyah" },
  { nomor: 57, id: "al-hadid", namaLatin: "Al-Hadid", namaArab: "الحديد", arti: "Besi", jumlahAyat: 29, tempatTurun: "Madaniyah" },
  { nomor: 58, id: "al-mujadila", namaLatin: "Al-Mujadila", namaArab: "المجادلة", arti: "Gugatan", jumlahAyat: 22, tempatTurun: "Madaniyah" },
  { nomor: 59, id: "al-hasyr", namaLatin: "Al-Hasyr", namaArab: "الحشر", arti: "Pengusiran", jumlahAyat: 24, tempatTurun: "Madaniyah" },
  { nomor: 60, id: "al-mumtahanah", namaLatin: "Al-Mumtahanah", namaArab: "الممتحنة", arti: "Wanita yang Diuji", jumlahAyat: 13, tempatTurun: "Madaniyah" },
  { nomor: 61, id: "as-saff", namaLatin: "As-Saff", namaArab: "الصف", arti: "Barisan", jumlahAyat: 14, tempatTurun: "Madaniyah" },
  { nomor: 62, id: "al-jumuah", namaLatin: "Al-Jumu'ah", namaArab: "الجمعة", arti: "Hari Jumat", jumlahAyat: 11, tempatTurun: "Madaniyah" },
  { nomor: 63, id: "al-munafiqun", namaLatin: "Al-Munafiqun", namaArab: "المنافقون", arti: "Orang-Orang Munafik", jumlahAyat: 11, tempatTurun: "Madaniyah" },
  { nomor: 64, id: "at-taghabun", namaLatin: "At-Taghabun", namaArab: "التغابن", arti: "Hari Ditampakkan Kerugian", jumlahAyat: 18, tempatTurun: "Madaniyah" },
  { nomor: 65, id: "at-talaq", namaLatin: "At-Talaq", namaArab: "الطلاق", arti: "Perceraian", jumlahAyat: 12, tempatTurun: "Madaniyah" },
  { nomor: 66, id: "at-tahrim", namaLatin: "At-Tahrim", namaArab: "التحريم", arti: "Mengharamkan", jumlahAyat: 12, tempatTurun: "Madaniyah" },
  { nomor: 67, id: "al-mulk", namaLatin: "Al-Mulk", namaArab: "الملك", arti: "Kerajaan", jumlahAyat: 30, tempatTurun: "Makkiyah" },
  { nomor: 68, id: "al-qalam", namaLatin: "Al-Qalam", namaArab: "القلم", arti: "Pena", jumlahAyat: 68, tempatTurun: "Makkiyah" },
  { nomor: 69, id: "al-haqqah", namaLatin: "Al-Haqqah", namaArab: "الحاقة", arti: "Hari Kiamat", jumlahAyat: 52, tempatTurun: "Makkiyah" },
  { nomor: 70, id: "al-maarij", namaLatin: "Al-Ma'arij", namaArab: "المعارج", arti: "Tempat Naik", jumlahAyat: 44, tempatTurun: "Makkiyah" },
  { nomor: 71, id: "nuh", namaLatin: "Nuh", namaArab: "نوح", arti: "Nabi Nuh", jumlahAyat: 28, tempatTurun: "Makkiyah" },
  { nomor: 72, id: "al-jinn", namaLatin: "Al-Jinn", namaArab: "الجن", arti: "Jin", jumlahAyat: 28, tempatTurun: "Makkiyah" },
  { nomor: 73, id: "al-muzzammil", namaLatin: "Al-Muzzammil", namaArab: "المزمل", arti: "Orang yang Berselimut", jumlahAyat: 20, tempatTurun: "Makkiyah" },
  { nomor: 74, id: "al-muddaththir", namaLatin: "Al-Muddaththir", namaArab: "المدثر", arti: "Orang yang Berkemul", jumlahAyat: 56, tempatTurun: "Makkiyah" },
  { nomor: 75, id: "al-qiyamah", namaLatin: "Al-Qiyamah", namaArab: "القيامة", arti: "Hari Kiamat", jumlahAyat: 40, tempatTurun: "Makkiyah" },
  { nomor: 76, id: "al-insan", namaLatin: "Al-Insan", namaArab: "الإنسان", arti: "Manusia", jumlahAyat: 31, tempatTurun: "Madaniyah" },
  { nomor: 77, id: "al-mursalat", namaLatin: "Al-Mursalat", namaArab: "المرسلات", arti: "Malaikat yang Diutus", jumlahAyat: 50, tempatTurun: "Makkiyah" },
  { nomor: 78, id: "an-naba", namaLatin: "An-Naba", namaArab: "النبإ", arti: "Berita Besar", jumlahAyat: 40, tempatTurun: "Makkiyah" },
  { nomor: 79, id: "an-nazi'at", namaLatin: "An-Nazi'at", namaArab: "النازعات", arti: "Malaikat yang Mencabut", jumlahAyat: 46, tempatTurun: "Makkiyah" },
  { nomor: 80, id: "abasa", namaLatin: "Abasa", namaArab: "عبس", arti: "Ia Bermuka Masam", jumlahAyat: 42, tempatTurun: "Makkiyah" },
  { nomor: 81, id: "at-takwir", namaLatin: "At-Takwir", namaArab: "التكوير", arti: "Menggulung", jumlahAyat: 29, tempatTurun: "Makkiyah" },
  { nomor: 82, id: "al-infitar", namaLatin: "Al-Infitar", namaArab: "الانفطار", arti: "Terbelah", jumlahAyat: 19, tempatTurun: "Makkiyah" },
  { nomor: 83, id: "al-mutaffifin", namaLatin: "Al-Mutaffifin", namaArab: "المطففين", arti: "Orang-Orang yang Curang", jumlahAyat: 36, tempatTurun: "Makkiyah" },
  { nomor: 84, id: "al-inshiqaq", namaLatin: "Al-Inshiqaq", namaArab: "الانشقاق", arti: "Terbelah", jumlahAyat: 25, tempatTurun: "Makkiyah" },
  { nomor: 85, id: "al-buruj", namaLatin: "Al-Buruj", namaArab: "البروج", arti: "Gugusan Bintang", jumlahAyat: 22, tempatTurun: "Makkiyah" },
  { nomor: 86, id: "at-tariq", namaLatin: "At-Tariq", namaArab: "الطارق", arti: "Yang Datang di Malam Hari", jumlahAyat: 17, tempatTurun: "Makkiyah" },
  { nomor: 87, id: "al-ala", namaLatin: "Al-A'la", namaArab: "الأعلى", arti: "Yang Paling Tinggi", jumlahAyat: 19, tempatTurun: "Makkiyah" },
  { nomor: 88, id: "al-ghashiyah", namaLatin: "Al-Ghashiyah", namaArab: "الغاشية", arti: "Hari Pembalasan", jumlahAyat: 26, tempatTurun: "Makkiyah" },
  { nomor: 89, id: "al-fajr", namaLatin: "Al-Fajr", namaArab: "الفجر", arti: "Waktu Fajar", jumlahAyat: 30, tempatTurun: "Makkiyah" },
  { nomor: 90, id: "al-balad", namaLatin: "Al-Balad", namaArab: "البلد", arti: "Negeri", jumlahAyat: 20, tempatTurun: "Makkiyah" },
  { nomor: 91, id: "asy-syams", namaLatin: "Asy-Syams", namaArab: "الشمس", arti: "Matahari", jumlahAyat: 15, tempatTurun: "Makkiyah" },
  { nomor: 92, id: "al-lail", namaLatin: "Al-Lail", namaArab: "الليل", arti: "Malam", jumlahAyat: 21, tempatTurun: "Makkiyah" },
  { nomor: 93, id: "ad-duha", namaLatin: "Ad-Duha", namaArab: "الضحى", arti: "Waktu Duha", jumlahAyat: 11, tempatTurun: "Makkiyah" },
  { nomor: 94, id: "asy-syarh", namaLatin: "Asy-Syarh", namaArab: "الشرح", arti: "Kelapangan Dada", jumlahAyat: 8, tempatTurun: "Makkiyah" },
  { nomor: 95, id: "at-tin", namaLatin: "At-Tin", namaArab: "التين", arti: "Buah Tin", jumlahAyat: 8, tempatTurun: "Makkiyah" },
  { nomor: 96, id: "al-alaq", namaLatin: "Al-'Alaq", namaArab: "العلق", arti: "Segumpal Darah", jumlahAyat: 19, tempatTurun: "Makkiyah" },
  { nomor: 97, id: "al-qadr", namaLatin: "Al-Qadr", namaArab: "القدر", arti: "Kemuliaan", jumlahAyat: 5, tempatTurun: "Makkiyah" },
  { nomor: 98, id: "al-bayyinah", namaLatin: "Al-Bayyinah", namaArab: "البينة", arti: "Bukti yang Nyata", jumlahAyat: 8, tempatTurun: "Madaniyah" },
  { nomor: 99, id: "az-zalzalah", namaLatin: "Az-Zalzalah", namaArab: "الزلزلة", arti: "Kegoncangan", jumlahAyat: 8, tempatTurun: "Madaniyah" },
  { nomor: 100, id: "al-adiyat", namaLatin: "Al-'Adiyat", namaArab: "العاديات", arti: "Kuda yang Berlari Kencang", jumlahAyat: 11, tempatTurun: "Makkiyah" },
  { nomor: 101, id: "al-qariah", namaLatin: "Al-Qari'ah", namaArab: "القارعة", arti: "Hari Kiamat", jumlahAyat: 11, tempatTurun: "Makkiyah" },
  { nomor: 102, id: "at-takathur", namaLatin: "At-Takathur", namaArab: "التكاثر", arti: "Bermegah-megahan", jumlahAyat: 8, tempatTurun: "Makkiyah" },
  { nomor: 103, id: "al-asr", namaLatin: "Al-'Asr", namaArab: "العصر", arti: "Masa / Waktu", jumlahAyat: 3, tempatTurun: "Makkiyah" },
  { nomor: 104, id: "al-humazah", namaLatin: "Al-Humazah", namaArab: "الهمزة", arti: "Pengumpat", jumlahAyat: 9, tempatTurun: "Makkiyah" },
  { nomor: 105, id: "al-fil", namaLatin: "Al-Fil", namaArab: "الفيل", arti: "Gajah", jumlahAyat: 5, tempatTurun: "Makkiyah" },
  { nomor: 106, id: "quraisy", namaLatin: "Quraisy", namaArab: "قريش", arti: "Suku Quraisy", jumlahAyat: 4, tempatTurun: "Makkiyah" },
  { nomor: 107, id: "al-maun", namaLatin: "Al-Ma'un", namaArab: "الماعون", arti: "Barang-Barang Berguna", jumlahAyat: 7, tempatTurun: "Makkiyah" },
  { nomor: 108, id: "al-kauthar", namaLatin: "Al-Kautsar", namaArab: "الكوثر", arti: "Nikmat yang Banyak", jumlahAyat: 3, tempatTurun: "Makkiyah" },
  { nomor: 109, id: "al-kafirun", namaLatin: "Al-Kafirun", namaArab: "الكافرون", arti: "Orang-Orang Kafir", jumlahAyat: 6, tempatTurun: "Makkiyah" },
  { nomor: 110, id: "an-nasr", namaLatin: "An-Nasr", namaArab: "النصر", arti: "Pertolongan", jumlahAyat: 3, tempatTurun: "Madaniyah" },
  { nomor: 111, id: "al-lahab", namaLatin: "Al-Lahab", namaArab: "اللهب", arti: "Gejolak Api", jumlahAyat: 5, tempatTurun: "Makkiyah" },
  { nomor: 112, id: "al-ikhlas", namaLatin: "Al-Ikhlas", namaArab: "الإخلاص", arti: "Kemurnian Keesaan Allah", jumlahAyat: 4, tempatTurun: "Makkiyah" },
  { nomor: 113, id: "al-falaq", namaLatin: "Al-Falaq", namaArab: "الفلق", arti: "Waktu Subuh", jumlahAyat: 5, tempatTurun: "Makkiyah" },
  { nomor: 114, id: "an-nas", namaLatin: "An-Nas", namaArab: "الناس", arti: "Manusia", jumlahAyat: 6, tempatTurun: "Makkiyah" },
]

export function getSurahDetailMeta(id: string): SurahDetailMeta | undefined {
  return SURAH_DETAIL_LIST.find((s) => s.id === id)
}
